version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rpa_network

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --settings=config.settings.dev &&
             python manage.py runserver 0.0.0.0:8000 --settings=config.settings.dev"
    volumes:
      - ./rpa_web:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GEMINI_API_KEY=AIzaSyA3-IYX6WJPxJtel6CzNCw8Y0G7WmyW72k
    depends_on:
      - redis
    networks:
      - rpa_network

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - ./rpa_web:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GEMINI_API_KEY=AIzaSyA3-IYX6WJPxJtel6CzNCw8Y0G7WmyW72k
    depends_on:
      - redis
      - web
    networks:
      - rpa_network

  celery-beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./rpa_web:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - GEMINI_API_KEY=AIzaSyA3-IYX6WJPxJtel6CzNCw8Y0G7WmyW72k
    depends_on:
      - redis
      - web
    networks:
      - rpa_network

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  rpa_network:
    driver: bridge
