import os
import django
import sys
from pathlib import Path
from datetime import date
from dotenv import load_dotenv

# Add project root to the Python path
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

# Load environment variables from .env.dev
dotenv_path = project_root / '.env.dev'
load_dotenv(dotenv_path=dotenv_path)

# Setup Django Environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")
django.setup()

from rpa_bot.models import DailyReport
from rpa_bot.ai_summarizer import AISummarizerService

def run_test():
    """
    This script tests the Telegram reporting functionality.
    It creates a dummy report and attempts to send it.
    """
    print("🚀 Starting Telegram notification test...")

    # 1. Initialize the summarizer service
    summarizer = AISummarizerService()

    # 2. Create a dummy report object for testing
    # In a real scenario, this would be generated by `generate_daily_report`
    print("📝 Creating a dummy test report...")
    test_report, created = DailyReport.objects.get_or_create(report_date=date.today())
    test_report.full_report = f"""
    - 🤖 TEST REPORT -
    
    นี่คือรายงานทดสอบการส่งแจ้งเตือนผ่าน Telegram
    
    หากคุณได้รับข้อความนี้ แสดงว่าการตั้งค่าทำงานถูกต้อง!
    
    - ข่าวหุ้น: ปกติ
    - ข่าวคริปโต: ปกติ
    - ข่าวเทคโนโลยี: ปกติ
    
    เวลาทดสอบ: {django.utils.timezone.now().strftime('%Y-%m-%d %H:%M:%S')}
    """
    test_report.is_completed = True

    # 3. Send the report
    print("📨 Attempting to send the test report via Telegram...")
    success = summarizer.send_report(test_report)

    if success:
        print("✅ Test report sent successfully!")
        print("Please check your Telegram for a message.")
    else:
        print("❌ Failed to send the test report.")
        print("Please check the console for errors and verify your .env.dev settings (TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID).")

if __name__ == "__main__":
    run_test()
