# Generated by Django 5.0.14 on 2025-10-24 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RPATask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อ Task")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="คำอธิบาย"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("google_search", "ค้นหา Google"),
                            ("screenshot", "จับภาพหน้าจอ"),
                            ("web_automation", "ระบบอัตโนมัติเว็บ"),
                            ("data_extraction", "ดึงข้อมูล"),
                        ],
                        default="google_search",
                        max_length=50,
                        verbose_name="ประเภท Task",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        default="https://www.google.com",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="คำค้นหา"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอดำเนินการ"),
                            ("running", "กำลังทำงาน"),
                            ("completed", "สำเร็จ"),
                            ("failed", "ล้มเหลว"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="ที่อยู่ภาพ"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, null=True, verbose_name="ผลลัพธ์"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="ข้อความ Error"
                    ),
                ),
                (
                    "delay_seconds",
                    models.IntegerField(default=3, verbose_name="หน่วงเวลา (วินาที)"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, verbose_name="ลองใหม่สูงสุด"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="จำนวนครั้งที่ลองแล้ว"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัพเดทเมื่อ"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="เริ่มเมื่อ"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="เสร็จเมื่อ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="สร้างโดย",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPA Task",
                "verbose_name_plural": "RPA Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(verbose_name="ข้อความ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="rpa_bot.rpatask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "ครั้งเดียว"),
                            ("daily", "ทุกวัน"),
                            ("weekly", "ทุกสัปดาห์"),
                            ("monthly", "ทุกเดือน"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(verbose_name="กำหนดเวลา")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="รันครั้งล่าสุด"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="rpa_bot.rpatask",
                    ),
                ),
            ],
            options={
                "verbose_name": "กำหนดเวลา Task",
                "verbose_name_plural": "กำหนดเวลา Tasks",
                "ordering": ["scheduled_time"],
            },
        ),
    ]
