# Generated by Django 5.0.6 on 2025-10-24 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpa_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="หัวข้อข่าว")),
                ("content", models.TextField(verbose_name="เนื้อหา")),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="รูปภาพ"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="ราคา",
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="การเปลี่ยนแปลง",
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="% เปลี่ยนแปลง",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, null=True, verbose_name="สรุปโดย AI"),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Sentiment"
                    ),
                ),
                ("published_at", models.DateTimeField(verbose_name="เผยแพร่เมื่อ")),
                (
                    "scraped_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ดึงข้อมูลเมื่อ"),
                ),
            ],
            options={
                "verbose_name": "ข่าว",
                "verbose_name_plural": "ข่าว",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อแหล่งข้อมูล")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stock_thai", "หุ้นไทย"),
                            ("stock_foreign", "หุ้นต่างประเทศ"),
                            ("crypto", "Bitcoin/Crypto"),
                            ("gold", "ราคาทองคำ"),
                            ("tech_ai", "Technology AI"),
                            ("tech_hardware", "Hardware"),
                            ("tech_software", "Software"),
                            ("football", "Football"),
                        ],
                        max_length=50,
                        verbose_name="หมวดหมู่",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "selector",
                    models.TextField(
                        blank=True, null=True, verbose_name="CSS Selector"
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="API Endpoint",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="API Key"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "แหล่งข้อมูลข่าว",
                "verbose_name_plural": "แหล่งข้อมูลข่าว",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(unique=True, verbose_name="วันที่รายงาน"),
                ),
                (
                    "stock_thai_summary",
                    models.TextField(blank=True, null=True, verbose_name="สรุปหุ้นไทย"),
                ),
                (
                    "stock_foreign_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="สรุปหุ้นต่างประเทศ"
                    ),
                ),
                (
                    "crypto_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="สรุป Bitcoin/Crypto"
                    ),
                ),
                (
                    "gold_summary",
                    models.TextField(blank=True, null=True, verbose_name="สรุปราคาทอง"),
                ),
                (
                    "tech_summary",
                    models.TextField(blank=True, null=True, verbose_name="สรุปข่าว Tech"),
                ),
                (
                    "football_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="สรุปข่าว Football"
                    ),
                ),
                (
                    "full_report",
                    models.TextField(blank=True, null=True, verbose_name="รายงานเต็ม"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="เสร็จสมบูรณ์"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="ส่งแล้ว")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ส่งเมื่อ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        related_name="reports",
                        to="rpa_bot.newsarticle",
                        verbose_name="บทความที่ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายงานประจำวัน",
                "verbose_name_plural": "รายงานประจำวัน",
                "ordering": ["-report_date"],
            },
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="rpa_bot.newssource",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["-published_at"], name="rpa_bot_new_publish_af07b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["source", "-published_at"],
                name="rpa_bot_new_source__505b9d_idx",
            ),
        ),
    ]
