# Generated by Django 5.0.6 on 2025-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpa_bot", "0002_newsarticle_newssource_dailyreport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyreport",
            name="stock_foreign_summary",
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="stock_china_summary",
            field=models.TextField(blank=True, null=True, verbose_name="สรุปหุ้นจีน"),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="stock_europe_summary",
            field=models.TextField(blank=True, null=True, verbose_name="สรุปหุ้นยุโรป"),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="stock_us_summary",
            field=models.TextField(blank=True, null=True, verbose_name="สรุปหุ้นอเมริกา"),
        ),
        migrations.AlterField(
            model_name="newssource",
            name="category",
            field=models.CharField(
                choices=[
                    ("stock_thai", "หุ้นไทย"),
                    ("stock_us", "หุ้นอเมริกา"),
                    ("stock_europe", "หุ้นยุโรป"),
                    ("stock_china", "หุ้นจีน"),
                    ("crypto", "Bitcoin/Crypto"),
                    ("gold", "ราคาทองคำ"),
                    ("tech_ai", "Technology AI"),
                    ("tech_hardware", "Hardware"),
                    ("tech_software", "Software"),
                    ("football", "Football"),
                ],
                max_length=50,
                verbose_name="หมวดหมู่",
            ),
        ),
    ]
