# Generated by Django 5.0.6 on 2025-10-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpa_bot", "0003_remove_dailyreport_stock_foreign_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=600, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="rpatask",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
