# Generated by Django 5.0.14 on 2025-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpa_bot", "0004_dailyreport_slug_newsarticle_slug_rpatask_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyreport",
            name="tech_summary",
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="ev_car_summary",
            field=models.TextField(blank=True, null=True, verbose_name="สรุปข่าว EV Car"),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="rocket_space_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="สรุปข่าว Rocket & Space"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="tech_ai_summary",
            field=models.TextField(blank=True, null=True, verbose_name="สรุปข่าว AI"),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="tech_hardware_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="สรุปข่าว Hardware"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="tech_software_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="สรุปข่าว Software"
            ),
        ),
        migrations.AlterField(
            model_name="newssource",
            name="category",
            field=models.CharField(
                choices=[
                    ("stock_thai", "หุ้นไทย"),
                    ("stock_us", "หุ้นอเมริกา"),
                    ("stock_europe", "หุ้นยุโรป"),
                    ("stock_china", "หุ้นจีน"),
                    ("crypto", "Bitcoin/Crypto"),
                    ("gold", "ราคาทองคำ"),
                    ("tech_ai", "Technology AI"),
                    ("tech_hardware", "Hardware"),
                    ("tech_software", "Software"),
                    ("football", "Football"),
                    ("ev_car", "EV Car"),
                    ("rocket_space", "Rocket & Space"),
                ],
                max_length=50,
                verbose_name="หมวดหมู่",
            ),
        ),
    ]
