# Generated by Django 5.0.14 on 2025-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpa_bot", "0005_remove_dailyreport_tech_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="detailed_analysis",
            field=models.TextField(
                blank=True, null=True, verbose_name="การวิเคราะห์แบบละเอียด"
            ),
        ),
    ]
