# Generated by Django 5.0.6 on 2025-10-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpa_bot", "0006_newsarticle_detailed_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="e_commerce_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="สรุป E-Commerce Deals"
            ),
        ),
        migrations.AlterField(
            model_name="newssource",
            name="category",
            field=models.CharField(
                choices=[
                    ("stock_thai", "หุ้นไทย"),
                    ("stock_us", "หุ้นอเมริกา"),
                    ("stock_europe", "หุ้นยุโรป"),
                    ("stock_china", "หุ้นจีน"),
                    ("crypto", "Bitcoin/Crypto"),
                    ("gold", "ราคาทองคำ"),
                    ("tech_ai", "Technology AI"),
                    ("tech_hardware", "Hardware"),
                    ("tech_software", "Software"),
                    ("football", "Football"),
                    ("ev_car", "EV Car"),
                    ("rocket_space", "Rocket & Space"),
                    ("e_commerce", "E-Commerce Deals"),
                ],
                max_length=50,
                verbose_name="หมวดหมู่",
            ),
        ),
    ]
