# Generated by Django 5.0.1 on 2025-10-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_bot', '0007_dailyreport_e_commerce_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อแบรนด์')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='โลโก้')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='เว็บไซต์')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'แบรนด์สินค้า',
                'verbose_name_plural': 'แบรนด์สินค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('keywords', models.TextField(blank=True, help_text='คำค้นหาหลายคำคั่นด้วย comma เช่น smartphone,มือถือ,โทรศัพท์', null=True, verbose_name='คำค้นหา')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('lazada', 'Lazada'), ('shopee', 'Shopee'), ('tiktok', 'TikTok Shop'), ('taobao', 'Taobao'), ('tmall', 'Tmall'), ('pinduoduo', 'Pinduoduo'), ('1688', '1688.com'), ('alibaba', 'Alibaba.com'), ('amazon', 'Amazon')], max_length=50, verbose_name='แพลตฟอร์ม')),
                ('product_url', models.URLField(max_length=1000, verbose_name='URL สินค้า')),
                ('product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product ID')),
                ('title', models.CharField(max_length=500, verbose_name='ชื่อสินค้า')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ราคาปัจจุบัน')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ราคาเต็ม')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ส่วนลด %')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ราคาต่ำสุด')),
                ('highest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ราคาสูงสุด')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='รูปภาพ')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='คะแนน')),
                ('reviews_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนรีวิว')),
                ('sold_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='ยอดขาย')),
                ('stock_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='สถานะสต็อก')),
                ('enable_price_alert', models.BooleanField(default=False, verbose_name='เปิดแจ้งเตือนราคา')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='แจ้งเตือนเมื่อราคาต่ำกว่าหรือเท่ากับราคานี้', max_digits=15, null=True, verbose_name='ราคาเป้าหมาย')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='ส่งการแจ้งเตือนแล้ว')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('is_available', models.BooleanField(default=True, verbose_name='มีสินค้า')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='ตรวจสอบล่าสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัพเดทเมื่อ')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_products', to='rpa_bot.productbrand', verbose_name='แบรนด์')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_products', to='rpa_bot.productcategory', verbose_name='หมวดหมู่')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_products', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'สินค้าที่ติดตาม',
                'verbose_name_plural': 'สินค้าที่ติดตาม',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ราคา')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ราคาเต็ม')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ส่วนลด %')),
                ('stock_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='สถานะสต็อก')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('tracked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='rpa_bot.trackedproduct', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'ประวัติราคา',
                'verbose_name_plural': 'ประวัติราคา',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackedproduct',
            index=models.Index(fields=['platform', 'is_active'], name='rpa_bot_tra_platfor_e0d896_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedproduct',
            index=models.Index(fields=['category', 'brand'], name='rpa_bot_tra_categor_3df1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedproduct',
            index=models.Index(fields=['-current_price'], name='rpa_bot_tra_current_8ce526_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['tracked_product', '-recorded_at'], name='rpa_bot_pri_tracked_43c263_idx'),
        ),
    ]
