# Generated by Django 5.0.1 on 2025-10-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_bot', '0008_productbrand_productcategory_trackedproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedproduct',
            name='platform',
            field=models.CharField(choices=[('lazada', 'Lazada'), ('shopee', 'Shopee'), ('tiktok', 'TikTok Shop'), ('taobao', 'Taobao'), ('tmall', 'Tmall'), ('pinduoduo', 'Pinduoduo'), ('jd', 'JD.com'), ('1688', '1688.com'), ('alibaba', 'Alibaba.com'), ('aliexpress', 'AliExpress'), ('amazon', 'Amazon')], max_length=50, verbose_name='แพลตฟอร์ม'),
        ),
    ]
