# Generated by Django 5.0.1 on 2025-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_bot', '0009_add_jd_aliexpress_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อเอกสาร')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='fa-file-alt', help_text='ชื่อ icon จาก Font Awesome เช่น fa-home, fa-rocket', max_length=100, verbose_name='Font Awesome Icon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('group', models.CharField(choices=[('getting_started', 'Getting Started'), ('core_features', 'Core Features'), ('advanced', 'Advanced')], default='getting_started', max_length=50, verbose_name='กลุ่ม')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'เอกสาร Documentation',
                'verbose_name_plural': 'เอกสาร Documentation',
                'ordering': ['group', 'order', 'title'],
            },
        ),
    ]
