# Generated by Django 5.0.1 on 2025-10-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_bot', '0010_docsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsection',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='เนื้อหาหลัก'),
        ),
        migrations.CreateModel(
            name='DocContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'หัวข้อ'), ('paragraph', 'ย่อหน้า'), ('code', 'โค้ด'), ('list', 'รายการ'), ('table', 'ตาราง'), ('alert', 'การแจ้งเตือน'), ('card', 'การ์ด'), ('image', 'รูปภาพ')], default='paragraph', max_length=50, verbose_name='ประเภทบล็อก')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับ')),
                ('heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='หัวข้อ')),
                ('content', models.TextField(blank=True, null=True, verbose_name='เนื้อหา')),
                ('code_language', models.CharField(blank=True, help_text='เช่น python, javascript, bash', max_length=50, null=True, verbose_name='ภาษาโค้ด')),
                ('alert_type', models.CharField(blank=True, choices=[('info', 'ข้อมูล'), ('success', 'สำเร็จ'), ('warning', 'คำเตือน'), ('danger', 'อันตราย')], max_length=20, null=True, verbose_name='ประเภทการแจ้งเตือน')),
                ('card_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อการ์ด')),
                ('card_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='ไอคอนการ์ด')),
                ('card_color', models.CharField(blank=True, help_text='เช่น blue, green, purple, red', max_length=50, null=True, verbose_name='สีการ์ด')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL รูปภาพ')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำอธิบายรูปภาพ')),
                ('list_items', models.JSONField(blank=True, help_text='JSON array ของรายการ', null=True, verbose_name='รายการ')),
                ('table_data', models.JSONField(blank=True, help_text='JSON object with headers and rows', null=True, verbose_name='ข้อมูลตาราง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='rpa_bot.docsection', verbose_name='ส่วนเอกสาร')),
            ],
            options={
                'verbose_name': 'บล็อกเนื้อหาเอกสาร',
                'verbose_name_plural': 'บล็อกเนื้อหาเอกสาร',
                'ordering': ['section', 'order'],
            },
        ),
    ]
