# Generated by Django 5.0.6 on 2025-10-26 17:03

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rpa_bot", "0011_docsection_content_doccontentblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docsection",
            name="content",
            field=django_summernote.fields.SummernoteTextField(
                blank=True, null=True, verbose_name="เนื้อหาหลัก"
            ),
        ),
    ]
